import type { TradeRouteGraph } from "./types";

/**
 * Global maritime trade route graph.
 *
 * Sources:
 * - Port/chokepoint coordinates and metadata from Wikidata SPARQL
 *   (query.wikidata.org) using Q-IDs cited per node.
 * - OSM IDs provided as fallback verification where available.
 * - Route importance weights are editorial estimates based on UNCTAD
 *   Review of Maritime Transport tonnage data.
 */
export const TRADE_ROUTE_GRAPH: TradeRouteGraph = {
  nodes: [
    // ── Major Hub Ports ──────────────────────────────────────────────────
    {
      id: "shanghai", name: "Shanghai", type: "hub", lat: 31.23, lon: 121.47, country: "CN", wikidataId: "Q8686",
      summary: "World's busiest container port, handling roughly 10% of global container traffic. A manufacturing and export megahub for China's Yangtze River Delta industrial region.",
      topExports: ["Electronics", "Machinery", "Textiles", "Chemicals", "Plastics"],
      topImports: ["Iron ore", "Crude oil", "Soybeans", "Copper", "Semiconductors"],
      throughput: "~49 M TEU/yr",
      globalRank: "#1 container port globally",
    },
    {
      id: "singapore", name: "Singapore", type: "hub", lat: 1.26, lon: 103.84, country: "SG", wikidataId: "Q334",
      summary: "The world's second-busiest container port and premier transshipment hub connecting East Asia, South Asia, and Europe. Singapore's port handles cargo from over 600 ports in 120 countries.",
      topExports: ["Refined petroleum", "Electronics", "Chemicals", "Machinery", "Gold"],
      topImports: ["Crude oil", "Electronics", "Machinery", "Refined petroleum", "Aircraft parts"],
      throughput: "~38 M TEU/yr",
      globalRank: "#2 container port globally",
    },
    {
      id: "rotterdam", name: "Rotterdam", type: "hub", lat: 51.90, lon: 4.50, country: "NL", wikidataId: "Q34370",
      summary: "Europe's largest port and its primary gateway for bulk commodities, petroleum, and containers. Rotterdam is the continent's biggest refining and petrochemical complex.",
      topExports: ["Petroleum products", "Chemicals", "Machinery", "Agri-products", "Metal scrap"],
      topImports: ["Crude oil", "Coal", "Iron ore", "Grain", "Containers"],
      throughput: "~15 M TEU / 470 Mt total/yr",
      globalRank: "#1 European port, #10 globally by TEU",
    },
    {
      id: "busan", name: "Busan", type: "hub", lat: 35.10, lon: 129.03, country: "KR", wikidataId: "Q16520",
      summary: "South Korea's largest port and a key transshipment hub for Northeast Asia. Busan connects Korea's export-oriented automotive and electronics industries to global markets.",
      topExports: ["Automobiles", "Electronics", "Machinery", "Steel", "Ships"],
      topImports: ["Crude oil", "LNG", "Coal", "Iron ore", "Semiconductors"],
      throughput: "~22 M TEU/yr",
      globalRank: "#6 container port globally",
    },
    {
      id: "hongkong", name: "Hong Kong", type: "hub", lat: 22.29, lon: 114.15, country: "HK", wikidataId: "Q8646",
      summary: "A major free-trade transshipment hub for southern China and the Pearl River Delta. Hong Kong's port benefits from its deep natural harbour and proximity to the world's largest manufacturing region.",
      topExports: ["Electronics", "Machinery", "Garments", "Jewellery", "Plastics"],
      topImports: ["Electronics", "Machinery", "Petroleum products", "Foodstuffs", "Metals"],
      throughput: "~16 M TEU/yr",
      globalRank: "#8 container port globally",
    },
    {
      id: "losangeles", name: "Los Angeles", type: "hub", lat: 33.74, lon: -118.27, country: "US", wikidataId: "Q65",
      summary: "The busiest container port in the US and the primary gateway for US consumer goods imports from Asia. Combined with neighboring Long Beach, it forms the largest port complex in the Western Hemisphere.",
      topExports: ["Aircraft parts", "Waste paper", "Agricultural products", "Cotton", "Chemicals"],
      topImports: ["Consumer electronics", "Clothing & apparel", "Furniture", "Automobiles", "Machinery"],
      throughput: "~10 M TEU/yr (LA alone)",
      globalRank: "#1 US container port, #18 globally",
    },
    {
      id: "dubai", name: "Jebel Ali (Dubai)", type: "hub", lat: 25.00, lon: 55.06, country: "AE", wikidataId: "Q1352282",
      summary: "The Middle East's largest port and the world's largest man-made harbour. Jebel Ali serves as the transshipment hub for the Gulf region and a key BRI (Belt and Road) logistics node.",
      topExports: ["Gold", "Petroleum products", "Aluminium", "Diamonds", "Machinery re-exports"],
      topImports: ["Machinery", "Electronics", "Gold", "Vehicles", "Pearls & precious stones"],
      throughput: "~14 M TEU/yr",
      globalRank: "#10 container port globally",
    },
    {
      id: "hamburg", name: "Hamburg", type: "hub", lat: 53.55, lon: 9.97, country: "DE", wikidataId: "Q1055",
      summary: "Germany's largest port and Northern Europe's second-biggest container port. Hamburg is the dominant entry point for German industrial imports and exports, with direct rail links to inland Europe and China.",
      topExports: ["Vehicles", "Chemicals", "Machinery", "Pharmaceutical products", "Aircraft parts"],
      topImports: ["Crude oil", "Consumer goods", "Electronics", "Coffee", "Copper"],
      throughput: "~8.3 M TEU/yr",
      globalRank: "#16 container port globally",
    },
    {
      id: "antwerp", name: "Antwerp", type: "hub", lat: 51.26, lon: 4.40, country: "BE", wikidataId: "Q12892",
      summary: "Europe's second-largest port by volume and the world's largest petrochemical complex outside Houston. Antwerp's central position gives deep-sea vessels direct access to the Rhine-Meuse-Scheldt delta hinterland.",
      topExports: ["Chemicals", "Petroleum products", "Vehicles", "Machinery", "Pharmaceuticals"],
      topImports: ["Crude oil", "LNG", "Chemicals", "Vehicles", "Electronics"],
      throughput: "~12 M TEU/yr",
      globalRank: "#13 container port globally",
    },
    {
      id: "newyork", name: "New York / Newark", type: "hub", lat: 40.67, lon: -74.04, country: "US", wikidataId: "Q60",
      summary: "The largest US East Coast port complex, serving the most populous US market. Post-Panama Canal expansion it can now receive ultra-large container vessels, boosting its import capacity.",
      topExports: ["Scrap metal", "Waste paper", "Chemicals", "Machinery", "Agricultural products"],
      topImports: ["Pharmaceuticals", "Vehicles", "Electronics", "Petroleum products", "Clothing"],
      throughput: "~8.1 M TEU/yr",
      globalRank: "#24 container port globally, #2 on US East Coast",
    },
    {
      id: "tokyo", name: "Tokyo", type: "hub", lat: 35.65, lon: 139.78, country: "JP", wikidataId: "Q1490",
      summary: "Japan's main container port and the economic heart of the Tokyo Bay industrial zone. Yokohama (co-located in the bay) handles additional bulk cargo, making the bay one of Asia's busiest port complexes.",
      topExports: ["Automobiles", "Electronics", "Machinery", "Precision instruments", "Steel"],
      topImports: ["LNG", "Crude oil", "Coal", "Foodstuffs", "Chemicals"],
      throughput: "~4.5 M TEU/yr",
      globalRank: "#14 container port in Japan's Tokyo Bay complex",
    },
    {
      id: "mumbai", name: "Mumbai (JNPT)", type: "hub", lat: 18.95, lon: 72.95, country: "IN", wikidataId: "Q1156",
      summary: "India's busiest container port via Jawaharlal Nehru Port Trust (JNPT). Mumbai is India's financial capital and the gateway for the country's vast western hinterland and manufacturing belt.",
      topExports: ["Textiles & garments", "Pharmaceuticals", "Chemicals", "Engineering goods", "Gems"],
      topImports: ["Crude oil", "Electronics", "Gold", "Coal", "Machinery"],
      throughput: "~5.8 M TEU/yr",
      globalRank: "#1 container port in India",
    },
    {
      id: "santos", name: "Santos", type: "hub", lat: -23.96, lon: -46.31, country: "BR", wikidataId: "Q170404",
      summary: "Latin America's largest port and Brazil's primary export gateway. Santos handles a massive bulk trade in agricultural commodities from Brazil's interior, especially soy, sugar, and orange juice.",
      topExports: ["Soybeans", "Sugar", "Beef & poultry", "Iron ore", "Coffee"],
      topImports: ["Fertilizers", "Electronics", "Machinery", "Salt", "Chemicals"],
      throughput: "~4.9 M TEU / 145 Mt total/yr",
      globalRank: "#1 port in Latin America by cargo volume",
    },
    {
      id: "raselkhair", name: "Ras al-Khair", type: "hub", lat: 27.48, lon: 49.25, country: "SA", wikidataId: "Q7294296",
      summary: "Saudi Arabia's industrial export port on the Arabian Gulf, hosting the world's largest phosphate export facility and a major aluminium smelter. A key node in the Kingdom's industrial diversification strategy.",
      topExports: ["Phosphate rock", "DAP fertilizer", "Aluminium", "Steel", "Petrochemicals"],
      topImports: ["Industrial equipment", "Machinery", "Construction materials", "Food", "Vehicles"],
      throughput: "~25 Mt/yr minerals + metals",
      globalRank: "World's largest phosphate export terminal",
    },
    {
      id: "rastanura", name: "Ras Tanura", type: "hub", lat: 26.64, lon: 50.16, country: "SA", wikidataId: "Q1749268",
      summary: "Saudi Aramco's flagship oil export terminal and the world's largest crude oil loading facility. Ras Tanura underpins global crude oil pricing and supply security.",
      topExports: ["Crude oil", "Refined petroleum products", "LPG", "Naphtha"],
      topImports: ["Industrial materials", "Plant equipment", "Food", "Construction goods"],
      throughput: "~330 Mt/yr crude oil",
      globalRank: "World's largest crude oil export terminal",
    },
    {
      id: "houston", name: "Houston", type: "hub", lat: 29.73, lon: -95.02, country: "US", wikidataId: "Q16555",
      summary: "The energy capital of the United States and the country's largest petrochemical export hub. Houston became the world's leading LNG exporter in 2023, reshaping global gas markets.",
      topExports: ["LNG", "Crude oil", "Petroleum products", "Petrochemicals", "Cotton"],
      topImports: ["Crude oil", "Steel", "Plastics", "Machinery", "Coffee"],
      throughput: "~155 Mt/yr total cargo",
      globalRank: "#1 US port by foreign waterborne cargo tonnage",
    },
    {
      id: "dalian", name: "Dalian", type: "hub", lat: 38.92, lon: 121.64, country: "CN", wikidataId: "Q73124",
      summary: "Northeast China's largest port and a key crude oil and iron ore import terminal for Chinese refineries and steel mills. Dalian also serves as the deepwater gateway for landlocked Northeast Asian markets.",
      topExports: ["Machinery", "Chemicals", "Steel products", "Petroleum products", "Electronics"],
      topImports: ["Iron ore", "Crude oil", "Grain", "LNG", "Coal"],
      throughput: "~14 M TEU / 350 Mt total/yr",
      globalRank: "Top 5 Chinese port by bulk cargo volume",
    },
    {
      id: "porthedland", name: "Port Hedland", type: "hub", lat: -20.31, lon: 118.58, country: "AU", wikidataId: "Q376158",
      summary: "The world's largest bulk export port by tonnage, shipping Pilbara iron ore almost exclusively to East Asian steel mills. Dust storms from ore stockpiles are visible from space.",
      topExports: ["Iron ore", "Salt", "Manganese ore"],
      topImports: ["Diesel fuel", "Industrial equipment", "Explosives"],
      throughput: "~580 Mt/yr iron ore",
      globalRank: "#1 bulk port by tonnage globally",
    },
    {
      id: "richards", name: "Richards Bay", type: "hub", lat: -28.80, lon: 32.03, country: "ZA", wikidataId: "Q978035",
      summary: "Sub-Saharan Africa's largest port by volume and the continent's premier coal export terminal. Richards Bay is also a key exporter of mineral sands, aluminium, and ferrochrome.",
      topExports: ["Thermal coal", "Mineral sands", "Aluminium", "Ferrochrome", "Woodchips"],
      topImports: ["Equipment", "Fuel", "Chemicals", "Machinery"],
      throughput: "~90 Mt/yr",
      globalRank: "#1 African port by bulk tonnage",
    },
    {
      id: "tubarao", name: "Tubarão (Vitória)", type: "hub", lat: -20.28, lon: -40.24, country: "BR", wikidataId: "Q2471310",
      summary: "Operated by Vale, Tubarão is one of the world's largest iron ore export terminals. The port ships ore from Brazil's Carajás mines on a 40-day voyage around the Cape to Chinese steel mills.",
      topExports: ["Iron ore pellets", "Steel slabs", "Iron ore"],
      topImports: ["Coal", "Coke", "Machinery", "Limestone"],
      throughput: "~120 Mt/yr iron ore",
      globalRank: "World's 2nd largest iron ore export terminal",
    },
    {
      id: "piraeus", name: "Piraeus", type: "hub", lat: 37.94, lon: 23.64, country: "GR", wikidataId: "Q140802",
      summary: "Southeastern Europe's largest container port, controlled by COSCO Shipping since 2016. Piraeus is the Belt and Road Initiative's western anchor, distributing Asian goods to the Balkans and Central Europe.",
      topExports: ["Petroleum products", "Chemicals", "Olive oil", "Pharmaceutical products", "Aluminum"],
      topImports: ["Electronics", "Machinery", "Vehicles", "Petroleum products", "Foodstuffs"],
      throughput: "~5.6 M TEU/yr",
      globalRank: "#1 Mediterranean container port by TEU",
    },
    {
      id: "colombo", name: "Colombo", type: "hub", lat: 6.94, lon: 79.84, country: "LK", wikidataId: "Q35381",
      summary: "South Asia's premier transshipment hub, ideally positioned on the east-west shipping lane between Europe and East Asia. Over 70% of cargo is transhipped rather than destined for Sri Lanka itself.",
      topExports: ["Textiles & garments", "Rubber products", "Coconut products", "Tea", "Gems"],
      topImports: ["Petroleum products", "Machinery", "Vehicles", "Foodstuffs", "Chemicals"],
      throughput: "~7 M TEU/yr",
      globalRank: "#1 transshipment port in South Asia",
    },
    {
      id: "laemchabang", name: "Laem Chabang", type: "hub", lat: 13.07, lon: 100.88, country: "TH", wikidataId: "Q6470770",
      summary: "Thailand's primary deep-sea container port and the industrial heartland of the Eastern Seaboard. Laem Chabang is a key export hub for Thai automobiles, electronics, and processed food.",
      topExports: ["Automobiles & parts", "Electronics", "Processed food", "Rubber", "Machinery"],
      topImports: ["Machinery", "Electronics", "Petroleum products", "Chemicals", "Steel"],
      throughput: "~8 M TEU/yr",
      globalRank: "#1 container port in Thailand",
    },
    {
      id: "felixstowe", name: "Felixstowe", type: "hub", lat: 51.95, lon: 1.33, country: "GB", wikidataId: "Q1169278",
      summary: "The UK's largest container port, handling approximately 36% of Britain's container traffic. Post-Brexit, Felixstowe has adapted to new customs regimes while remaining the country's dominant import gateway.",
      topExports: ["Chemicals", "Vehicles", "Machinery", "Pharmaceutical products", "Whisky"],
      topImports: ["Electronics", "Clothing", "Machinery", "Furniture", "Toys"],
      throughput: "~3.8 M TEU/yr",
      globalRank: "#1 UK container port",
    },
    {
      id: "portklang", name: "Port Klang", type: "hub", lat: 3.00, lon: 101.39, country: "MY", wikidataId: "Q1479026",
      summary: "Malaysia's national port and the 12th busiest container port globally. Port Klang serves as a secondary transshipment hub complementing Singapore, offering lower costs for intra-Asian cargo.",
      topExports: ["Electronics", "Palm oil", "Petroleum products", "Rubber products", "Chemicals"],
      topImports: ["Electronics", "Machinery", "Petroleum products", "Steel", "Vehicles"],
      throughput: "~14 M TEU/yr",
      globalRank: "#12 container port globally",
    },
    {
      id: "savannah", name: "Savannah", type: "hub", lat: 32.08, lon: -81.09, country: "US", wikidataId: "Q38022",
      summary: "The third-largest US container port and the fastest-growing major port in North America. Savannah serves the booming US Southeast manufacturing belt, including major automotive and distribution centre clusters.",
      topExports: ["Paper products", "Vehicles & parts", "Agricultural products", "Kaolin clay", "Machinery"],
      topImports: ["Consumer goods", "Furniture", "Clothing & apparel", "Electronics", "Carpets"],
      throughput: "~5.6 M TEU/yr",
      globalRank: "#3 US container port",
    },
    {
      id: "alexandria", name: "Alexandria", type: "hub", lat: 31.20, lon: 29.92, country: "EG", wikidataId: "Q87",
      summary: "Egypt's largest port and the main gateway for the country's vital food and commodity imports. Alexandria's proximity to the Suez Canal makes it a strategic node for Mediterranean and Red Sea trade.",
      topExports: ["Petroleum products", "Cotton", "Chemicals", "Citrus fruits", "Marble"],
      topImports: ["Grain & wheat", "Vehicles", "Machinery", "Iron & steel", "Petroleum"],
      throughput: "~2.5 M TEU / 60 Mt total/yr",
      globalRank: "#1 Egyptian port by container volume",
    },
    {
      id: "kaohsiung", name: "Kaohsiung", type: "hub", lat: 22.61, lon: 120.29, country: "TW", wikidataId: "Q34660",
      summary: "Taiwan's largest port and a critical node for semiconductor and electronics exports. Kaohsiung connects Taiwan's world-dominant chip industry (TSMC) to global supply chains.",
      topExports: ["Electronics & semiconductors", "Petrochemicals", "Machinery", "Steel", "Plastics"],
      topImports: ["Crude oil", "Coal", "Iron ore", "Electronic components", "Liquefied natural gas"],
      throughput: "~10.6 M TEU/yr",
      globalRank: "#1 Taiwanese port",
    },
    {
      id: "novorossiysk", name: "Novorossiysk", type: "hub", lat: 44.72, lon: 37.77, country: "RU", wikidataId: "Q25498",
      summary: "Russia's largest port by cargo volume and the primary export terminal for Urals crude oil from the Caspian pipeline. Subject to Western sanctions since 2022, Novorossiysk has pivoted to India and China.",
      topExports: ["Crude oil", "Grain & wheat", "Coal", "Metal products", "Fertilizers"],
      topImports: ["Metals", "Equipment", "Foodstuffs", "Consumer goods", "Chemicals"],
      throughput: "~150 Mt/yr",
      globalRank: "#1 Russian port by cargo volume",
    },
    {
      id: "vancouver", name: "Vancouver", type: "hub", lat: 49.29, lon: -123.11, country: "CA", wikidataId: "Q24639",
      summary: "Canada's largest port and the primary export terminal for western Canadian bulk commodities. Vancouver links Canada's Prairie grain, Rocky Mountain coal, and potash industries to Pacific markets.",
      topExports: ["Coal", "Grain & canola", "Potash", "Lumber & wood pulp", "Sulphur"],
      topImports: ["Automobiles", "Electronics", "Petroleum products", "Machinery", "Containers"],
      throughput: "~3.5 M TEU / 147 Mt total/yr",
      globalRank: "#1 Canadian port by total cargo volume",
    },

    // ── Chokepoints ──────────────────────────────────────────────────────
    {
      id: "suez", name: "Suez Canal", type: "chokepoint", lat: 30.46, lon: 32.35, wikidataId: "Q899",
      summary: "The world's most important artificial waterway, connecting the Mediterranean to the Red Sea. Its closure forces vessels on a 10,000 km detour around Africa, adding ~2 weeks and major fuel costs.",
      dailyVessels: 50,
      tradeSharePct: "12–13% of global trade",
      widthKm: 0.3,
      primaryCommodities: ["Containers", "Crude oil", "LNG", "Grain", "Petroleum products"],
      controlledBy: "Egypt (Suez Canal Authority)",
    },
    {
      id: "panama", name: "Panama Canal", type: "chokepoint", lat: 9.08, lon: -79.68, wikidataId: "Q7325",
      summary: "The only sea route linking the Pacific and Atlantic oceans without circumnavigating Cape Horn. Its lock size limits vessel draft, making it a critical bottleneck for LNG and grain shipments from the US Gulf.",
      dailyVessels: 40,
      tradeSharePct: "5% of global trade",
      widthKm: 0.055,
      primaryCommodities: ["LNG", "Containers", "Grain", "Automobiles", "Coal"],
      controlledBy: "Panama (Panama Canal Authority)",
    },
    {
      id: "malacca", name: "Strait of Malacca", type: "chokepoint", lat: 2.50, lon: 101.20, wikidataId: "Q40832",
      summary: "The world's busiest and most strategically vital sea lane, connecting the Indian Ocean to the South China Sea. Its closure would force oil tankers and container ships on lengthy detours through the Lombok or Sunda Straits.",
      dailyVessels: 274,
      tradeSharePct: "25% of global trade",
      widthKm: 2.7,
      primaryCommodities: ["Crude oil", "LNG", "Containers", "Coal", "Iron ore"],
      controlledBy: "Indonesia / Malaysia / Singapore",
    },
    {
      id: "hormuz", name: "Strait of Hormuz", type: "chokepoint", lat: 26.57, lon: 56.25, wikidataId: "Q34675",
      summary: "The only sea exit from the Persian Gulf, through which flows roughly 21% of global oil consumption daily. Iran has repeatedly threatened closure as a geopolitical weapon, which would trigger immediate global energy shock.",
      dailyVessels: 40,
      tradeSharePct: "~21% of global oil consumption",
      widthKm: 55,
      primaryCommodities: ["Crude oil", "LNG", "Petroleum products", "LPG"],
      controlledBy: "Oman / Iran",
    },
    {
      id: "babelmandeb", name: "Bab el-Mandeb", type: "chokepoint", lat: 12.58, lon: 43.33, wikidataId: "Q131739",
      summary: "The gateway between the Red Sea and the Gulf of Aden. Houthi missile and drone attacks since late 2023 have diverted hundreds of vessels around the Cape of Good Hope, raising insurance rates and voyage costs.",
      dailyVessels: 50,
      tradeSharePct: "~10% of global trade",
      widthKm: 29,
      primaryCommodities: ["Containers", "Crude oil", "LNG", "Grain", "Petroleum products"],
      controlledBy: "Djibouti / Yemen / Eritrea",
    },
    {
      id: "gibraltar", name: "Strait of Gibraltar", type: "chokepoint", lat: 35.97, lon: -5.50, wikidataId: "Q3040",
      summary: "The narrow gateway between the Atlantic Ocean and the Mediterranean Sea. One of the world's busiest shipping lanes, it is also a key chokepoint for Russian oil shipments transiting to Atlantic markets.",
      dailyVessels: 300,
      tradeSharePct: "~10% of global trade",
      widthKm: 14,
      primaryCommodities: ["Containers", "Crude oil", "LNG", "Bulk", "Petroleum products"],
      controlledBy: "Spain / UK (Gibraltar)",
    },
    {
      id: "bosporus", name: "Bosporus", type: "chokepoint", lat: 41.12, lon: 29.05, wikidataId: "Q131859",
      summary: "The sole maritime exit from the Black Sea, running through Istanbul. The Turkish Straits Convention limits warship transit, while Russian oil and Ukrainian grain trade depend critically on unimpeded passage.",
      dailyVessels: 123,
      tradeSharePct: "~3% of global trade",
      widthKm: 0.7,
      primaryCommodities: ["Crude oil", "Grain & wheat", "Steel", "Petroleum products", "Coal"],
      controlledBy: "Turkey",
    },
    {
      id: "danish", name: "Danish Straits", type: "chokepoint", lat: 55.95, lon: 11.30, wikidataId: "Q187894",
      summary: "The collection of narrow straits (Great Belt, Little Belt, Øresund) giving access to the Baltic Sea. All Baltic energy exports — Russian LNG and oil, Norwegian pipeline gas — must transit these shallow waters.",
      dailyVessels: 95,
      tradeSharePct: "~2% of global trade",
      widthKm: 3.7,
      primaryCommodities: ["Crude oil", "LNG", "Grain", "Coal", "Containers"],
      controlledBy: "Denmark / Sweden",
    },
    {
      id: "capegoodhope", name: "Cape of Good Hope", type: "chokepoint", lat: -34.36, lon: 18.47, wikidataId: "Q4092",
      summary: "The stormy southern tip of Africa and the primary bypass route when the Suez Canal or Bab el-Mandeb is disrupted. The 2023–24 Houthi crisis caused a sharp surge in Cape roundings, adding ~10 transit days per voyage.",
      dailyVessels: 55,
      tradeSharePct: "~4–8% of global trade (rises sharply during Suez disruptions)",
      widthKm: 1200,
      primaryCommodities: ["Containers", "Crude oil", "Bulk", "LNG", "Petroleum products"],
      controlledBy: "International waters (South Africa EEZ nearby)",
    },
    {
      id: "capehorn", name: "Cape Horn", type: "chokepoint", lat: -55.98, lon: -67.27, wikidataId: "Q4628",
      summary: "The southernmost tip of South America and one of the world's most treacherous maritime passages. Cape Horn connects the Pacific and Atlantic oceans and serves as the bypass when the Panama Canal is unavailable for over-sized vessels.",
      dailyVessels: 8,
      tradeSharePct: "~1% of global trade",
      widthKm: 800,
      primaryCommodities: ["Bulk carriers", "LNG", "Container ships (over-Panamax)"],
      controlledBy: "International waters (Chile EEZ nearby)",
    },
    {
      id: "lombok", name: "Lombok Strait", type: "chokepoint", lat: -8.47, lon: 115.72, wikidataId: "Q578668",
      summary: "A deep-water alternative to the Strait of Malacca for large tankers and bulk carriers. The Lombok Strait can accommodate very large crude carriers (VLCCs) that are too large for Malacca's shallow 25m depth.",
      dailyVessels: 45,
      tradeSharePct: "~3% of global trade",
      widthKm: 35,
      primaryCommodities: ["Crude oil (VLCC)", "Iron ore", "LNG", "Coal", "Containers"],
      controlledBy: "Indonesia",
    },
    {
      id: "dover", name: "Strait of Dover", type: "chokepoint", lat: 51.04, lon: 1.42, wikidataId: "Q37453",
      summary: "The world's busiest international shipping lane, with over 500 ships per day using the separation scheme. Dover is also the UK's primary ferry link to continental Europe, carrying passengers and lorries.",
      dailyVessels: 500,
      tradeSharePct: "~10% of global trade",
      widthKm: 34,
      primaryCommodities: ["Containers", "Bulk", "Petroleum", "RoRo (ferries)", "Tankers"],
      controlledBy: "UK / France",
    },
    {
      id: "taiwan", name: "Taiwan Strait", type: "chokepoint", lat: 24.00, lon: 119.50, wikidataId: "Q132376",
      summary: "One of the world's most geopolitically sensitive sea lanes, through which roughly half the global containership fleet transits annually. A Chinese blockade of Taiwan would be catastrophic for global semiconductor supply chains.",
      dailyVessels: 90,
      tradeSharePct: "~50% of global containership fleet annually",
      widthKm: 130,
      primaryCommodities: ["Containers", "Electronics", "Semiconductors", "Bulk", "Tankers"],
      controlledBy: "International waters",
    },
    {
      id: "mozambique", name: "Mozambique Channel", type: "chokepoint", lat: -17.00, lon: 41.00, wikidataId: "Q178524",
      summary: "A 1,700 km-wide channel between Madagascar and mainland Africa. It serves as an alternative Cape bypass route and a key transit corridor for tankers trading between the Persian Gulf and Atlantic markets.",
      dailyVessels: 11,
      tradeSharePct: "~2% of global trade",
      widthKm: 450,
      primaryCommodities: ["Crude oil", "LNG (Mozambique LNG)", "Bulk", "Containers"],
      controlledBy: "Mozambique / Madagascar",
    },
    {
      id: "sunda", name: "Sunda Strait", type: "chokepoint", lat: -6.10, lon: 105.75, wikidataId: "Q184395",
      summary: "A secondary deep-water passage between the Indian Ocean and South China Sea, used mainly by southbound vessels as an alternative to Lombok Strait. Geologically active — the 2018 Anak Krakatau eruption briefly closed it.",
      dailyVessels: 20,
      tradeSharePct: "~1% of global trade",
      widthKm: 24,
      primaryCommodities: ["Crude oil", "LNG", "Bulk", "Containers"],
      controlledBy: "Indonesia",
    },

    // ── Intermediate Waypoints (open ocean) ──────────────────────────────
    { id: "wp_arabiansea",     name: "Arabian Sea",        type: "waypoint", lat: 15.0,   lon: 65.0 },
    { id: "wp_bayofbengal",    name: "Bay of Bengal",       type: "waypoint", lat: 10.0,   lon: 85.0 },
    { id: "wp_southchina",     name: "South China Sea",     type: "waypoint", lat: 12.0,   lon: 114.0 },
    { id: "wp_medeast",        name: "Eastern Mediterranean", type: "waypoint", lat: 33.0, lon: 30.0 },
    { id: "wp_medwest",        name: "Western Mediterranean", type: "waypoint", lat: 37.0, lon: 5.0 },
    { id: "wp_northatlantic",  name: "North Atlantic",      type: "waypoint", lat: 45.0,   lon: -30.0 },
    { id: "wp_midatlantic",    name: "Mid Atlantic",        type: "waypoint", lat: 20.0,   lon: -35.0 },
    { id: "wp_southatlantic",  name: "South Atlantic",      type: "waypoint", lat: -10.0,  lon: -10.0 },
    { id: "wp_northpacific",   name: "North Pacific",       type: "waypoint", lat: 35.0,   lon: -170.0 },
    { id: "wp_indianocean",    name: "Indian Ocean",        type: "waypoint", lat: -5.0,   lon: 75.0 },
    { id: "wp_gulfofaden",     name: "Gulf of Aden",        type: "waypoint", lat: 12.0,   lon: 48.0 },
    { id: "wp_persiangulf",    name: "Persian Gulf",        type: "waypoint", lat: 26.0,   lon: 52.0 },
    { id: "wp_redsea",         name: "Red Sea",             type: "waypoint", lat: 20.0,   lon: 38.0 },
    { id: "wp_eastchina",      name: "East China Sea",      type: "waypoint", lat: 30.0,   lon: 125.0 },
    { id: "wp_gulfofmexico",   name: "Gulf of Mexico",      type: "waypoint", lat: 25.0,   lon: -90.0 },
    { id: "wp_caribbean",      name: "Caribbean Sea",       type: "waypoint", lat: 15.0,   lon: -75.0 },
    { id: "wp_westafrica",     name: "West Africa",         type: "waypoint", lat: 5.0,    lon: -5.0 },
    { id: "wp_northsea",       name: "North Sea",           type: "waypoint", lat: 55.0,   lon: 3.0 },
    { id: "wp_blacksea",       name: "Black Sea",           type: "waypoint", lat: 43.0,   lon: 35.0 },
    { id: "wp_southeast_indian", name: "SE Indian Ocean",   type: "waypoint", lat: -20.0,  lon: 95.0 },
  ],

  routes: [
    // ────────────────────────── CONTAINER ─────────────────────────────────
    {
      id: "asia-europe-container",
      name: "Asia → Europe (Main Line)",
      category: "container",
      importance: 5,
      startHub: "shanghai",
      endHub: "rotterdam",
      waypoints: ["shanghai", "hongkong", "wp_southchina", "singapore", "malacca", "wp_indianocean", "wp_arabiansea", "wp_gulfofaden", "babelmandeb", "wp_redsea", "suez", "wp_medeast", "wp_medwest", "gibraltar", "dover", "rotterdam"],
      whyItMatters: "Carries ~25% of global container trade; the world's busiest liner corridor.",
      keyChokepoints: ["malacca", "suez", "gibraltar"],
      sourceTrace: ["https://www.wikidata.org/wiki/Q899", "https://www.wikidata.org/wiki/Q40832", "https://www.wikidata.org/wiki/Q3040"],
    },
    {
      id: "transpacific-container",
      name: "Transpacific (Asia → US West Coast)",
      category: "container",
      importance: 5,
      startHub: "shanghai",
      endHub: "losangeles",
      waypoints: ["shanghai", "busan", "wp_northpacific", "losangeles"],
      whyItMatters: "Largest bilateral trade lane by container volume; US import lifeline.",
      keyChokepoints: [],
      sourceTrace: ["https://www.wikidata.org/wiki/Q8686", "https://www.wikidata.org/wiki/Q65"],
    },
    {
      id: "asia-med-container",
      name: "Asia → Mediterranean",
      category: "container",
      importance: 4,
      startHub: "shanghai",
      endHub: "piraeus",
      waypoints: ["shanghai", "hongkong", "wp_southchina", "singapore", "malacca", "wp_indianocean", "wp_arabiansea", "wp_gulfofaden", "babelmandeb", "wp_redsea", "suez", "wp_medeast", "piraeus"],
      whyItMatters: "COSCO hub at Piraeus feeds SE Europe; BRI western anchor.",
      keyChokepoints: ["malacca", "suez"],
      sourceTrace: ["https://www.wikidata.org/wiki/Q899", "https://www.wikidata.org/wiki/Q140802"],
    },
    {
      id: "transatlantic-container",
      name: "Transatlantic (Europe → US East Coast)",
      category: "container",
      importance: 4,
      startHub: "rotterdam",
      endHub: "newyork",
      waypoints: ["rotterdam", "dover", "wp_northatlantic", "newyork"],
      whyItMatters: "High-value manufactured goods corridor between NATO allies.",
      keyChokepoints: ["dover"],
      sourceTrace: ["https://www.wikidata.org/wiki/Q34370", "https://www.wikidata.org/wiki/Q60"],
    },
    {
      id: "intra-asia-container",
      name: "Intra-Asia (China → SE Asia)",
      category: "container",
      importance: 4,
      startHub: "shanghai",
      endHub: "laemchabang",
      waypoints: ["shanghai", "hongkong", "wp_southchina", "laemchabang"],
      whyItMatters: "Fastest-growing container lane; ASEAN manufacturing integration.",
      keyChokepoints: ["taiwan"],
      sourceTrace: ["https://www.wikidata.org/wiki/Q8686", "https://www.wikidata.org/wiki/Q6470770"],
    },
    {
      id: "asia-useast-container",
      name: "Asia → US East Coast (via Suez)",
      category: "container",
      importance: 3,
      startHub: "shanghai",
      endHub: "savannah",
      waypoints: ["shanghai", "hongkong", "wp_southchina", "singapore", "malacca", "wp_indianocean", "wp_arabiansea", "wp_gulfofaden", "babelmandeb", "wp_redsea", "suez", "wp_medeast", "wp_medwest", "gibraltar", "wp_northatlantic", "savannah"],
      whyItMatters: "Growing alternative to Transpacific + rail; avoids West Coast congestion.",
      keyChokepoints: ["malacca", "suez", "gibraltar"],
      sourceTrace: ["https://www.wikidata.org/wiki/Q899", "https://www.wikidata.org/wiki/Q38022"],
    },
    {
      id: "southamerica-europe-container",
      name: "South America → Europe",
      category: "container",
      importance: 3,
      startHub: "santos",
      endHub: "antwerp",
      waypoints: ["santos", "wp_southatlantic", "wp_midatlantic", "wp_northatlantic", "dover", "antwerp"],
      whyItMatters: "Brazil-EU agricultural and manufactured goods exchange.",
      keyChokepoints: ["dover"],
      sourceTrace: ["https://www.wikidata.org/wiki/Q170404", "https://www.wikidata.org/wiki/Q12892"],
    },

    // ────────────────────────── ENERGY ────────────────────────────────────
    {
      id: "persian-gulf-asia-oil",
      name: "Persian Gulf → East Asia (Crude Oil)",
      category: "energy",
      importance: 5,
      startHub: "rastanura",
      endHub: "dalian",
      waypoints: ["rastanura", "wp_persiangulf", "hormuz", "wp_arabiansea", "wp_indianocean", "malacca", "wp_southchina", "dalian"],
      whyItMatters: "~17 mb/d of crude transits Hormuz; China/Japan/Korea dependent.",
      keyChokepoints: ["hormuz", "malacca"],
      sourceTrace: ["https://www.wikidata.org/wiki/Q34675", "https://www.wikidata.org/wiki/Q40832"],
    },
    {
      id: "persian-gulf-europe-oil",
      name: "Persian Gulf → Europe (Crude Oil)",
      category: "energy",
      importance: 4,
      startHub: "rastanura",
      endHub: "rotterdam",
      waypoints: ["rastanura", "wp_persiangulf", "hormuz", "wp_arabiansea", "wp_gulfofaden", "babelmandeb", "wp_redsea", "suez", "wp_medeast", "wp_medwest", "gibraltar", "dover", "rotterdam"],
      whyItMatters: "EU refinery supply line; disruption at Suez or Hormuz spikes Brent prices.",
      keyChokepoints: ["hormuz", "babelmandeb", "suez"],
      sourceTrace: ["https://www.wikidata.org/wiki/Q34675", "https://www.wikidata.org/wiki/Q899"],
    },
    {
      id: "usgulf-asia-lng",
      name: "US Gulf → East Asia (LNG)",
      category: "energy",
      importance: 4,
      startHub: "houston",
      endHub: "tokyo",
      waypoints: ["houston", "wp_gulfofmexico", "wp_caribbean", "panama", "wp_northpacific", "tokyo"],
      whyItMatters: "US is world's largest LNG exporter; Panama Canal transit critical.",
      keyChokepoints: ["panama"],
      sourceTrace: ["https://www.wikidata.org/wiki/Q7325", "https://www.wikidata.org/wiki/Q1490"],
    },
    {
      id: "russia-europe-oil",
      name: "Russia → Europe (Crude & Products)",
      category: "energy",
      importance: 3,
      startHub: "novorossiysk",
      endHub: "rotterdam",
      waypoints: ["novorossiysk", "wp_blacksea", "bosporus", "wp_medeast", "wp_medwest", "gibraltar", "dover", "rotterdam"],
      whyItMatters: "Bosporus bottleneck for Urals crude; sanctions reroute via Cape.",
      keyChokepoints: ["bosporus", "gibraltar"],
      sourceTrace: ["https://www.wikidata.org/wiki/Q131859", "https://www.wikidata.org/wiki/Q25498"],
    },
    {
      id: "westafrica-asia-oil",
      name: "West Africa → East Asia (Crude Oil)",
      category: "energy",
      importance: 3,
      startHub: "richards",
      endHub: "dalian",
      waypoints: ["richards", "capegoodhope", "wp_southeast_indian", "malacca", "wp_southchina", "dalian"],
      whyItMatters: "Nigerian/Angolan crude to Chinese refineries; avoids Suez entirely.",
      keyChokepoints: ["capegoodhope", "malacca"],
      sourceTrace: ["https://www.wikidata.org/wiki/Q4092", "https://www.wikidata.org/wiki/Q40832"],
    },
    {
      id: "persian-gulf-india-oil",
      name: "Persian Gulf → India (Crude Oil)",
      category: "energy",
      importance: 4,
      startHub: "rastanura",
      endHub: "mumbai",
      waypoints: ["rastanura", "wp_persiangulf", "hormuz", "wp_arabiansea", "mumbai"],
      whyItMatters: "India imports ~85% of crude; Hormuz is a single point of failure.",
      keyChokepoints: ["hormuz"],
      sourceTrace: ["https://www.wikidata.org/wiki/Q34675", "https://www.wikidata.org/wiki/Q1156"],
    },

    // ────────────────────────── BULK ──────────────────────────────────────
    {
      id: "australia-china-ironore",
      name: "Australia → China (Iron Ore)",
      category: "bulk",
      importance: 5,
      startHub: "porthedland",
      endHub: "dalian",
      waypoints: ["porthedland", "wp_southeast_indian", "lombok", "wp_southchina", "dalian"],
      whyItMatters: "Single largest dry-bulk trade by tonnage; ~900 Mt/yr of iron ore.",
      keyChokepoints: ["lombok"],
      sourceTrace: ["https://www.wikidata.org/wiki/Q376158", "https://www.wikidata.org/wiki/Q578668"],
    },
    {
      id: "brazil-china-ironore",
      name: "Brazil → China (Iron Ore)",
      category: "bulk",
      importance: 4,
      startHub: "tubarao",
      endHub: "dalian",
      waypoints: ["tubarao", "wp_southatlantic", "capegoodhope", "wp_southeast_indian", "malacca", "wp_southchina", "dalian"],
      whyItMatters: "Vale's 40-day voyage; Cape route makes it price-sensitive to freight rates.",
      keyChokepoints: ["capegoodhope", "malacca"],
      sourceTrace: ["https://www.wikidata.org/wiki/Q2471310", "https://www.wikidata.org/wiki/Q4092"],
    },
    {
      id: "usgulf-asia-grain",
      name: "US Gulf → East Asia (Grain)",
      category: "bulk",
      importance: 3,
      startHub: "houston",
      endHub: "shanghai",
      waypoints: ["houston", "wp_gulfofmexico", "wp_caribbean", "panama", "wp_northpacific", "shanghai"],
      whyItMatters: "US corn and soybean exports; Panama Canal draft limits Panamax loads.",
      keyChokepoints: ["panama"],
      sourceTrace: ["https://www.wikidata.org/wiki/Q7325", "https://www.wikidata.org/wiki/Q8686"],
    },
    {
      id: "blacksea-med-grain",
      name: "Black Sea → Mediterranean (Grain)",
      category: "bulk",
      importance: 3,
      startHub: "novorossiysk",
      endHub: "alexandria",
      waypoints: ["novorossiysk", "wp_blacksea", "bosporus", "wp_medeast", "alexandria"],
      whyItMatters: "Ukraine/Russia wheat to MENA; Bosporus congestion and war risk.",
      keyChokepoints: ["bosporus"],
      sourceTrace: ["https://www.wikidata.org/wiki/Q131859", "https://www.wikidata.org/wiki/Q87"],
    },
    {
      id: "southafrica-europe-coal",
      name: "South Africa → Europe (Coal)",
      category: "bulk",
      importance: 2,
      startHub: "richards",
      endHub: "rotterdam",
      waypoints: ["richards", "wp_southatlantic", "wp_westafrica", "wp_midatlantic", "wp_northatlantic", "dover", "rotterdam"],
      whyItMatters: "Thermal coal for EU power; declining but spikes during energy crises.",
      keyChokepoints: ["dover"],
      sourceTrace: ["https://www.wikidata.org/wiki/Q978035", "https://www.wikidata.org/wiki/Q34370"],
    },
    {
      id: "australia-india-coal",
      name: "Australia → India (Coal)",
      category: "bulk",
      importance: 3,
      startHub: "porthedland",
      endHub: "mumbai",
      waypoints: ["porthedland", "wp_southeast_indian", "wp_indianocean", "wp_arabiansea", "mumbai"],
      whyItMatters: "Coking coal for Indian steel; Lombok Strait alternative when Malacca congested.",
      keyChokepoints: ["lombok"],
      sourceTrace: ["https://www.wikidata.org/wiki/Q376158", "https://www.wikidata.org/wiki/Q1156"],
    },

    // ────────────────────────── STRATEGIC ─────────────────────────────────
    {
      id: "cape-route-strategic",
      name: "Cape Route (Asia → Europe bypass)",
      category: "strategic",
      importance: 4,
      startHub: "singapore",
      endHub: "rotterdam",
      waypoints: ["singapore", "wp_indianocean", "mozambique", "capegoodhope", "wp_southatlantic", "wp_westafrica", "wp_midatlantic", "wp_northatlantic", "dover", "rotterdam"],
      whyItMatters: "Fallback when Suez/Red Sea is disrupted; adds ~10 days and significant fuel cost.",
      keyChokepoints: ["capegoodhope", "mozambique"],
      sourceTrace: ["https://www.wikidata.org/wiki/Q4092", "https://www.wikidata.org/wiki/Q178524"],
    },
    {
      id: "taiwan-strait-strategic",
      name: "Taiwan Strait Corridor",
      category: "strategic",
      importance: 5,
      startHub: "shanghai",
      endHub: "hongkong",
      waypoints: ["shanghai", "wp_eastchina", "taiwan", "wp_southchina", "hongkong"],
      whyItMatters: "~50% of global container fleet transits annually; geopolitical flashpoint.",
      keyChokepoints: ["taiwan"],
      sourceTrace: ["https://www.wikidata.org/wiki/Q132376"],
    },
    {
      id: "bosporus-grain-strategic",
      name: "Bosporus Grain Corridor",
      category: "strategic",
      importance: 4,
      startHub: "novorossiysk",
      endHub: "piraeus",
      waypoints: ["novorossiysk", "wp_blacksea", "bosporus", "piraeus"],
      whyItMatters: "Critical chokepoint for Black Sea grain; Turkish Straits Convention limits transit.",
      keyChokepoints: ["bosporus"],
      sourceTrace: ["https://www.wikidata.org/wiki/Q131859", "https://www.wikidata.org/wiki/Q140802"],
    },
    {
      id: "hormuz-strategic",
      name: "Strait of Hormuz Energy Corridor",
      category: "strategic",
      importance: 5,
      startHub: "rastanura",
      endHub: "mumbai",
      waypoints: ["rastanura", "wp_persiangulf", "hormuz", "wp_arabiansea", "mumbai"],
      whyItMatters: "~21% of global oil consumption transits daily; most watched chokepoint on earth.",
      keyChokepoints: ["hormuz"],
      sourceTrace: ["https://www.wikidata.org/wiki/Q34675"],
    },
    {
      id: "babelmandeb-strategic",
      name: "Bab el-Mandeb Corridor",
      category: "strategic",
      importance: 4,
      startHub: "dubai",
      endHub: "piraeus",
      waypoints: ["dubai", "hormuz", "wp_arabiansea", "wp_gulfofaden", "babelmandeb", "wp_redsea", "suez", "wp_medeast", "piraeus"],
      whyItMatters: "Houthi attacks force reroutes around the Cape; connects Gulf to Med.",
      keyChokepoints: ["babelmandeb", "suez", "hormuz"],
      sourceTrace: ["https://www.wikidata.org/wiki/Q131739", "https://www.wikidata.org/wiki/Q899"],
    },
  ],
};

/** Node lookup map for O(1) access. */
export const NODE_MAP = new Map(TRADE_ROUTE_GRAPH.nodes.map((n) => [n.id, n]));
